### ISSUE TITLE
Index File Names

### ISSUE THREAD

**Issue by theduke** [kamadorueda/nixpkgs-db#3]
I currently use [nix-index](https://github.com/bennofs/nix-index) to find packages containing specific files. 

For example,  to find a package containing the `wasm2wat` binary I can run `nix-locate wasm2wat`.

The downside is that this requires building a local index, which takes quite a bit of time.

Since this project already indexes all packages, adding files in a package and providing a file search would be awesome.

**Comment by kamadorueda** [comment]
Just to let you know guys that I'm migrating this repository to: https://github.com/kamadorueda/four-shells

This issue is now at: https://github.com/kamadorueda/four-shells/issues/2

And by the way we are now hosted at https://4shells.com/nixdb, with an improved user interface

Old links redirect there anyway :)
